import type { DialogProps } from "@radix-ui/react-dialog";
import { redirect } from "next/navigation";
import { useCallback, useEffect, useState } from "react";

import {
  useCreateProject,
  useDeleteProject,
  useProjectQuery,
  useUpdateProject,
} from "@/client/biz-logic/project";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { capitalizeFirstLetter } from "@/core/utils/text";
import { api } from "@/trpc/react";

import {
  Field,
  FieldContent,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "../ui/field";
import { Input } from "../ui/input";
import { Spinner } from "../ui/spinner";

export function EditProjectDialog({
  children,
  mode,
  ...props
}: DialogProps & { mode: "edit" | "create"; projectId?: string }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [verificationError, setVerificationError] = useState<string | null>(
    null,
  );
  const { data: project } = useProjectQuery({
    projectId: mode === "edit" ? props.projectId : undefined,
  });
  const [projectName, setProjectName] = useState("");
  const [projectId, setProjectId] = useState("");
  const [autoGeneratedProjectId, setAutoGeneratedProjectId] = useState(false);
  const verifyProjectId = api.project.verifyProjectId.useMutation();
  const createProject = useCreateProject();
  const updateProject = useUpdateProject();
  const deleteProject = useDeleteProject();

  useEffect(() => {
    if (project) {
      setProjectName(project.name);
      setProjectId(project.id);
    }
  }, [project]);
  useEffect(() => {
    if (mode === "create") {
      if (projectName === "") {
        setAutoGeneratedProjectId(true);
      }
      if (autoGeneratedProjectId) {
        setProjectId(generateDefaultProjectId(projectName));
      }
    }
  }, [autoGeneratedProjectId, mode, projectId, projectName]);

  const handleSubmitProject = useCallback(async () => {
    setBusy(true);
    setVerificationError(null);
    setError(null);
    try {
      const { verified, message } = await verifyProjectId.mutateAsync({
        projectId,
        verifyExists: mode === "create",
      });
      if (!verified) {
        setVerificationError(message!);
        setBusy(false);
        return;
      }
    } catch (error) {
      setVerificationError((error as Error).message);
      setBusy(false);
      return;
    }
    if (mode === "create") {
      try {
        await createProject({
          projectId,
          data: {
            name: projectName,
            generations: [],
          },
        });
        props.onOpenChange?.(false);
        redirect(`/workspace/projects/${projectId}/gallery`);
      } catch (e) {
        if (e instanceof Error && e.message === "NEXT_REDIRECT") {
          throw e;
        }
        setError((e as Error).message);
      } finally {
        setBusy(false);
      }
    } else if (mode === "edit") {
      try {
        await updateProject({
          projectId,
          data: {
            name: projectName,
          },
        });
        props.onOpenChange?.(false);
        redirect(`/workspace/projects/${projectId}/gallery`);
      } catch (e) {
        if (e instanceof Error && e.message === "NEXT_REDIRECT") {
          throw e;
        }
        setError((e as Error).message);
      } finally {
        setBusy(false);
      }
    }
  }, [
    createProject,
    mode,
    projectId,
    projectName,
    props,
    updateProject,
    verifyProjectId,
  ]);
  const handleDeleteProject = useCallback(async () => {
    try {
      await deleteProject({ projectId });
      props.onOpenChange?.(false);
      redirect(`/workspace/projects`);
    } catch (e) {
      if (e instanceof Error && e.message === "NEXT_REDIRECT") {
        throw e;
      }
      setError((e as Error).message);
    }
  }, [deleteProject, projectId, props]);

  return (
    <Dialog {...props}>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>
            {mode === "create" ? "Create" : "Edit"} project
          </DialogTitle>
          <DialogDescription>
            Click &quot;
            {capitalizeFirstLetter(mode === "create" ? "create" : "save")}&quot;
            to apply or cancel to leave it unchanged.
          </DialogDescription>
        </DialogHeader>
        <form className="py-2">
          <FieldGroup>
            <Field>
              <FieldLabel>Project name</FieldLabel>
              <FieldDescription>
                The display name of your project.
              </FieldDescription>
              <FieldContent>
                <Input
                  disabled={busy}
                  placeholder="Any name you like"
                  value={projectName}
                  onChange={(e) => setProjectName(e.target.value)}
                />
              </FieldContent>
            </Field>
            <Field>
              <FieldLabel>Project ID</FieldLabel>
              <FieldDescription>
                An unique identifier for your project. Also used as the folder
                name.
              </FieldDescription>
              <FieldContent>
                <Input
                  placeholder="Lower-case letters, numbers, underscores, and hyphens only"
                  value={projectId}
                  disabled={busy || mode === "edit"}
                  onChange={(e) => {
                    setAutoGeneratedProjectId(false);
                    setProjectId(e.target.value);
                  }}
                />
              </FieldContent>
              {verificationError && (
                <FieldError>{verificationError}</FieldError>
              )}
            </Field>
            {error && <FieldError>{error}</FieldError>}
          </FieldGroup>
        </form>
        <DialogFooter>
          <div className="flex w-full justify-between">
            <div className="flex h-full items-center">
              {mode === "edit" && projectId !== "default" && (
                <Button variant="destructive" onClick={handleDeleteProject}>
                  Delete
                </Button>
              )}
            </div>
            <div className="flex h-full items-center gap-2">
              <DialogClose asChild>
                <Button variant="outline">Cancel</Button>
              </DialogClose>
              <DialogClose asChild>
                <Button
                  type="submit"
                  disabled={
                    busy || projectId.trim() === "" || projectName.trim() === ""
                  }
                  onClick={handleSubmitProject}
                >
                  {busy && <Spinner />}
                  {mode === "create" ? "Create" : "Save"}
                </Button>
              </DialogClose>
            </div>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function generateDefaultProjectId(name: string) {
  return name.trim().replace(/\s/g, "-").toLowerCase();
}
